import { ReactNode } from "react";
import "../styles/globals.css"
import vazirFont from "@/constants/localFont";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${vazirFont.variable} font-sans`}>
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
